### ISSUE TITLE
Customize the voting button color in the library

### ISSUE THREAD

**Issue by HeiChaJ** [JoTechOfficial/FluentForSteamLibrarySkin#1]
The color saturation of the vote button is too high, I have searched for a long time in those three configuration files but can't find the corresponding parameter, how can I change it?

**Comment by JoTechOfficial** [comment]
Could you include a picture so I know what vote button?

**Comment by HeiChaJ** [comment]
![image](https://user-images.githubusercontent.com/22045978/221852749-80873af5-6a18-4bdc-9569-8307288de6d0.png)
As shown in the picture

**Comment by JoTechOfficial** [comment]
Don't know how to change that, must be apart of the code that is imported in the css file. Unless you can find a hex code that match those colors and reference my code.
